[all:vars]
ansible_python_interpreter=/usr/bin/python3

[image_nfs]
image_nfs_0 ansible_host=192.168.1.212 ansible_user=ansible

[file_nfs]
file_nfs_0 ansible_host=192.168.1.216 ansible_user=ansible

[minio]
minio_0 ansible_host=192.168.1.220 ansible_user=ansible

[local_dns]
local_dns_0 ansible_host=192.168.1.207 ansible_user=ansible

[firefly]
firefly_0 ansible_host=192.168.1.210 ansible_user=ansible

[video_nfs]
video_nfs_0 ansible_host=192.168.1.218 ansible_user=ansible

[music_nfs]
music_nfs_0 ansible_host=192.168.1.221 ansible_user=ansible

[k3s_master]
k3s_master_0 ansible_host=192.168.1.214 ansible_user=ansible

[k3s_worker_1]
k3s_worker_1_0 ansible_host=192.168.1.215 ansible_user=ansible
